### ISSUE TITLE
[run] Enable `--production`, `--webapps`, `--rest` via environment variable

### ISSUE THREAD

**Issue by ceefour** [camunda/docker-camunda-bpm-platform#136]
Currently these settings are not configurable via environment variable, but need to use run args.

Run args tend to be harder to configure in non "pure Docker" environments, e.g. Kubernetes.

For example, my first attempt:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
spec:
  selector:
    matchLabels:
      app: camunda
  replicas: 1
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:run-7.13.0-alpha4
          args:
            - --production
```

failed with:

```
[FATAL tini (7)] exec --production failed: No such file or directory
```

I need to diagnose this and perhaps I will succeed, but this is adding effort and perhaps other edge cases.

If these _must_ be configured by command line args, then please add docs in `README.md` and/or https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/ to set them in Kubernetes. Thank you :)

**Comment by AndreaGiardini** [comment]
Hello @ceefour 
I think replacing
```
          args:
            - --production
```
with:
```
          args:
            - ./camunda
            - --production
```
Let us know if that's not the case :)

**Comment by ceefour** [comment]
Thanks @AndreaGiardini , this made it work:

```yaml
        - name: camunda
          image: camunda/camunda-bpm-platform:run-7.13.0-alpha4
          # https://github.com/camunda/camunda-bpm-platform/blob/master/distro/run/assembly/resources/production.yml
          args: ['./camunda.sh', '--production']
```

I still prefer environment variable, but even if not, please make it part of Camunda BPM Run documentation.
